### ISSUE TITLE
Expire transaction-specific Ledis records

### ISSUE THREAD

**Issue by opoudjis** [nsip/nias2#11]
Give them an hour

**Comment by opoudjis** [comment]
Giving them 16 mins.

**Comment by matt-farmer** [comment]
Nick, 

That’s nowhere near long enough, on a less capable machine the transactions could easily still be running after 30 minutes. Expiry should be in hours or days, we only want to prevent a slow memory bloat over time not manage the memory aggressively.

Cheers,

Matt
