### ISSUE TITLE
Ledis transaction timeouts

### ISSUE THREAD

**Issue by matt-farmer** [nsip/nias2#13]
Timeouts are set to 16 minutes. Most windows machines will take at least this long to process a large (1million) record file, meaning data will be removed before the transaction completes.

Expiry is only needed to prevent eventual large files being created on disk, no urgent memory pressures, just good ongoing housekeeping.

Therefore expiry of old data should be in hours or days, not minutes.

No release should go out until this is resolved as it will appear that the software has stopped working for windows users.

**Comment by opoudjis** [comment]
Set expiration time span in lib/lookup.go to 

    const KEY_EXPIRATION = 100000

Which is 27 hrs.
