### ISSUE TITLE
2 types of writing tests not easily differentiated in UI for NAPRR NIASv1.02

### ISSUE THREAD

**Issue by lpecchiar** [nsip/nias2#69]
In the school score summary, domain scores and participation tabs the writing and writing -alternate are not easily distinguishable unless the user drills down to look at the detail of the line.

![image](https://user-images.githubusercontent.com/30399925/41832334-f930698a-788e-11e8-85fb-37b22d867c96.png)

**Comment by opoudjis** [comment]
Functionality retired, so closing.
